// Here we configure our routes

@routeURL = http://localhost:5211

GET {{routeURL}}/weatherforecast/
Accept: application/json

###

// Every action should be declared in this file
// 1- We made the Http method {{the base url, who is routeURL}}/the path of the route
// who is routeURL/api/Books
// 2- We made => Accept: appliaction/json thats meen the server must return 
// json format data to the client

GET {{routeURL}}/api/Books/
Accept: application/json

###

GET {{routeURL}}/api/Books/id
Accept: application/json

### 

POST {{routeURL}}/api/Books
// Content-Type : meen the data sending by the client must be in json format
Content-Type: application/json
{
  "Id": 10,
  "Title": "Hello js",
  "Author": "Mohammed",
  "YearPublished": 2004
}

###

PUT {{routeURL}}/api/Books/1
Content-Type: application/json
{
  "Title": "Hello js",
  "Author": "Mohammed",
  "YearPublished": 2002
}

###

DELETE {{routeURL}}/api/Books/1
Accept: application/json